import { STATES } from "./states.js";

export const ALLOWED_TRANSITIONS = {
  [STATES.INTRO]: [STATES.TASK_CHECK, STATES.CALLBACK_TIME],
  [STATES.TASK_CHECK]: [STATES.TASK_DONE, STATES.TASK_PENDING, STATES.RETRY_TASK_CHECK],
  [STATES.RETRY_TASK_CHECK]: [STATES.TASK_DONE, STATES.TASK_PENDING, STATES.ESCALATE],
  [STATES.TASK_PENDING]: [STATES.PROBLEM_RECORDED],
  [STATES.CALLBACK_TIME]: [STATES.CALLBACK_CONFIRM],
};

export function isValidTransition(current, next) {
  if (!current) return true;
  return ALLOWED_TRANSITIONS[current]?.includes(next);
}
